### ISSUE TITLE
I couldn't understand your data structure for lookup-map

### ISSUE THREAD

**Issue by Kistar** [amslabtech/state_lattice_planner#17]
your look up table is a map of maps of param, and the two keys are v0 and k0. What are they? In your .csv file I've seen that there are many nodes with the same v0 and k0. With map only one of them can be stored. So how does this work? I am totally confused.

**Comment by Taka-Kazu** [comment]
The lookup table is a map of maps of a vector of params. So the number of the vector of param corresponding to a pair of v0 and k0 is one.
https://github.com/amslabtech/state_lattice_planner/blob/918f2d2f2a70f1468c58e578cbe8d3b0a188a9a4/state_lattice_planner/include/state_lattice_planner/lookup_table_utils.h#L14-L24

v0 is the current linear velocity of the robot, and k0 is the current yaw-rate of the robot.
The params in the lookup table are v0, k0, target state(x, y, yaw), and pre-calculated control params(km, kf, sf).
So, given robot velocity and target state, we can get pre-calculated control params in a similar condition from the lookup table.
The pre-calculated control params are used as the initial param for calculations that optimize the robot trajectory.
