### ISSUE TITLE
trajectory_generator_diff_drive.h:6:23:fatal error: Eigen/Dense:  No such file or directory

### ISSUE THREAD

**Issue by YouShaoze** [amslabtech/state_lattice_planner#18]
when I catkin_make this src/ file, it shows:
In file included from /home/ysz/state_lattice_planner/src/state_lattice_planner/trajectory_generator/src/trajectory_generator_diff_drive.cpp:1:0:
/home/ysz/state_lattice_planner/src/state_lattice_planner/trajectory_generator/include/trajectory_generator/trajectory_generator_diff_drive.h:6:23: fatal error: Eigen/Dense: No such file or directory
compilation terminated.
In file included from /home/ysz/state_lattice_planner/src/state_lattice_planner/trajectory_generator/src/motion_model_diff_drive.cpp:1:0:
/home/ysz/state_lattice_planner/src/state_lattice_planner/trajectory_generator/include/trajectory_generator/motion_model_diff_drive.h:6:23: fatal error: Eigen/Dense: No such file or directory
compilation terminated.
But I found them in the file path.

**Comment by Taka-Kazu** [comment]
What is the installation path of Eigen in your environment?
If it is `/usr/local/include/eigen3`, to run `ln -sf /usr/local/eigen3/Eigen /usr/include/Eigen` will resolve the error.
