### ISSUE TITLE
Minor bug about the trajectory distance integration

### ISSUE THREAD

**Issue by nkuwenjian** [amslabtech/state_lattice_planner#20]
First of all, thank you for sharing the code.

In function make_velocity_profile of motion_model_diff_drive.cpp file, I think s_profile_[0] is not zero, but v0 * dt. Actually, the integrated distance in initial pose should be zero.

Best,

Jian Wen

**Comment by Taka-Kazu** [comment]
Thank you for your report!

You are right, it's a bug.

I think the bug was fixed by PR(#21).

Please check it again.
