### ISSUE TITLE
How to Use this planner 

### ISSUE THREAD

**Issue by YouShaoze** [amslabtech/state_lattice_planner#24]
I try to use it in clearpath husky robot，but in the rviz I cannot find the /local_goal topic and the /cmd_vel  could not be published.
![20200731160057](https://user-images.githubusercontent.com/26811225/89013790-18c62900-d347-11ea-945b-d5bc5e3b6d28.jpg)

**Comment by Taka-Kazu** [comment]
It looks like you are launching a planner node using `state_lattice_planner/launch/local_planner.launch`.
In the launch file, some topic names are remapped. 
https://github.com/amslabtech/state_lattice_planner/blob/6793de79b272c20fa9948a4a65b8627e9b33c6b9/launch/local_planner.launch#L39-L42
So `cmd_vel` is remapped to `/local_path/cmd_vel`. If you prefer the name `cmd_vel`, you can simply delete the remap.

Unchecking the `Dead sinks` and `Leaf topics` checkboxes (at the top left of `rqt_graph`)  will help you to debug.

And although this is not directly related to the topic at hand, you don't need to run `lookup_table_generator` with the planner.
The `lookup_table_generator` is implemented as a ros node, but it doesn't communicate with other nodes and generates a lookup table (csv file) from the given parameters.
