### ISSUE TITLE
how to use it?need something else? No tf data.  Actual error: Fixed Frame [XXX] does not exist

### ISSUE THREAD

**Issue by seekku** [amslabtech/state_lattice_planner#26]
hello, i roslaunch local_planner.launch and trajectory_viewer.launch.
i changed the remap in local_planner.launch
but i met a mistake. 
No tf data.  Actual error: Fixed Frame [XXX] does not exist
do i need something else?

**Comment by yinflight** [comment]
No tf data.  Actual error: Fixed Frame [base_link] does not exist
